In [1]:
import array

In [2]:
array.array('i', list(range(10)))

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np

In [5]:
a = np.array(['retre', 'rtre', 5, 6])

In [9]:
a.dtype

dtype('<U5')

In [10]:
a = np.array([1, 2, 3, 4, 5, 6], dtype="float32")

In [11]:
a

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [13]:
a = np.array([range(i, i + 3) for i in [2, 4, 6]])

In [14]:
a.ndim

2

In [15]:
a.shape

(3, 3)

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full([2,3], 10.10)

array([[10.1, 10.1, 10.1],
       [10.1, 10.1, 10.1]])

In [50]:
r = np.arange(0, 10, 2)

In [22]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.random.random([2,3])

array([[0.87489156, 0.50966773, 0.36888758],
       [0.32378462, 0.88863463, 0.0675469 ]])

In [26]:
np.random.normal(10, 20, [2,3]) # 1st agr: mean, 2nd arg: std

array([[35.17738626, 14.0927654 , 45.19325647],
       [21.20563893, -2.48716296, 28.97680264]])

In [48]:
e = np.eye(5)

In [65]:
array = np.random.randint(10, 20, [2,3])

In [42]:
np.random.seed(0)

In [47]:
np.random.randint(0, 10, [3,3])

array([[3, 5, 0],
       [2, 3, 8],
       [1, 3, 3]])

In [49]:
e.size

25

In [54]:
r = np.arange(0, 50, 2)

In [55]:
r

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [56]:
r[2:10:2]

array([ 4,  8, 12, 16])

In [57]:
r[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10,  8,  6,  4,  2,  0])

In [67]:
array

array([[11, 15, 19],
       [13, 10, 15]])

In [66]:
array[::-1, ::-1] # reverse dimension

array([[15, 10, 13],
       [19, 15, 11]])

In [68]:
array = np.random.normal(10, 20, [5,7])

In [69]:
array[:3, :2] # 3 rows, 2 cols

array([[-5.52040934, 10.53738497],
       [ 9.75310373, 10.84242981],
       [32.41209314,  5.51922441]])

In [70]:
array

array([[ -5.52040934,  10.53738497,  31.11674266,   8.53633152,
         -3.31441324,   9.11775184,   2.73465961],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [72]:
# view, copy
view = array.view()

In [73]:
view

array([[ -5.52040934,  10.53738497,  31.11674266,   8.53633152,
         -3.31441324,   9.11775184,   2.73465961],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [74]:
copy = array.copy()

In [75]:
copy

array([[ -5.52040934,  10.53738497,  31.11674266,   8.53633152,
         -3.31441324,   9.11775184,   2.73465961],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [76]:
copy[0] = 0

In [77]:
copy

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [78]:
array

array([[ -5.52040934,  10.53738497,  31.11674266,   8.53633152,
         -3.31441324,   9.11775184,   2.73465961],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [79]:
view[0] = 0

In [80]:
view

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [81]:
array

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  9.75310373,  10.84242981,  49.18591782,   6.03148608,
         16.61068811, -18.71656812,  10.55056634],
       [ 32.41209314,   5.51922441,   1.59633221,  29.99659387,
         18.62068298,  -3.01825744, -19.97480773],
       [-14.61269938,  13.88014383,  -9.96764708,   2.64724794,
         44.74398633,  21.87225505,  -0.84727163],
       [-24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [83]:
array.shape

(5, 7)

In [84]:
newArray = array.reshape(7, 5)

In [85]:
newArray

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   9.75310373,  10.84242981,
         49.18591782],
       [  6.03148608,  16.61068811, -18.71656812,  10.55056634,
         32.41209314],
       [  5.51922441,   1.59633221,  29.99659387,  18.62068298,
         -3.01825744],
       [-19.97480773, -14.61269938,  13.88014383,  -9.96764708,
          2.64724794],
       [ 44.74398633,  21.87225505,  -0.84727163, -24.39344757,
         -1.57817572],
       [ 38.53897101,  15.5399381 ,  25.79334261,  16.44148227,
         24.00784754]])

In [86]:
newArray.shape

(7, 5)

In [87]:
newArray1 = array.reshape(1, 35)

In [88]:
newArray1

array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   9.75310373,
         10.84242981,  49.18591782,   6.03148608,  16.61068811,
        -18.71656812,  10.55056634,  32.41209314,   5.51922441,
          1.59633221,  29.99659387,  18.62068298,  -3.01825744,
        -19.97480773, -14.61269938,  13.88014383,  -9.96764708,
          2.64724794,  44.74398633,  21.87225505,  -0.84727163,
        -24.39344757,  -1.57817572,  38.53897101,  15.5399381 ,
         25.79334261,  16.44148227,  24.00784754]])

In [89]:
newArray2 = array.reshape(35, 1)

In [91]:
newArray2

array([[  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  0.        ],
       [  9.75310373],
       [ 10.84242981],
       [ 49.18591782],
       [  6.03148608],
       [ 16.61068811],
       [-18.71656812],
       [ 10.55056634],
       [ 32.41209314],
       [  5.51922441],
       [  1.59633221],
       [ 29.99659387],
       [ 18.62068298],
       [ -3.01825744],
       [-19.97480773],
       [-14.61269938],
       [ 13.88014383],
       [ -9.96764708],
       [  2.64724794],
       [ 44.74398633],
       [ 21.87225505],
       [ -0.84727163],
       [-24.39344757],
       [ -1.57817572],
       [ 38.53897101],
       [ 15.5399381 ],
       [ 25.79334261],
       [ 16.44148227],
       [ 24.00784754]])

In [96]:
a1 = np.array([[1,2,3],[1,2,3]])
a2 = np.array([[4,5,6],[4,5,6]])

In [103]:
c = np.concatenate([a1,a2])
c

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [104]:
c1 = np.concatenate([a1,a2], axis=1)
c1

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [105]:
c.shape

(4, 3)

In [106]:
c1.shape

(2, 6)

In [107]:
a3 = np.array([1,2,3])

In [111]:
vs = np.vstack([a3, a2])

In [112]:
vs

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [113]:
hs = np.hstack([a1, a2])

In [114]:
hs

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [115]:
hs*5

array([[ 5, 10, 15, 20, 25, 30],
       [ 5, 10, 15, 20, 25, 30]])